spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/test
    username: PUBLIC
    password:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDB106Dialect
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
server:
  port=8090